version: '2'

services:

    nginx:
        restart: "!restart!"
        build:
            context: ./php/fpm/nginx
            args:
                - PHP_UPSTREAM=php_fpm
        environment:
            - VIRTUAL_HOST=!domain!
        volumes_from:
            - volumes_source
        volumes:
            - ./logs/nginx/:/var/log/nginx
        links:
            - php_fpm

    php_fpm:
        restart: "!restart!"
        build:
            context: ./php/fpm
            dockerfile: dockerfile-!php!/Dockerfile
        volumes_from:
            - volumes_source

    mysql:
        restart: "!restart!"
        build:
            context: ./mysql
            dockerfile: ./dockerfile-!mysql!/Dockerfile
        volumes:
            - ../db/mysql:/var/lib/mysql
            - ../db/backup:/var/www/backup
        environment:
            MYSQL_DATABASE: site
            MYSQL_USER: site
            MYSQL_PASSWORD: site
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "!dbport!:3306"
        expose:
            - "3306"

    volumes_source:
        build: ./volumes/application
        volumes:
            - ../www/:/var/www/html
            - ./php/fpm/hosts:/etc/hosts
            - ./php/fpm/cacert.pem:/usr/lib/ssl/private/cacert.pem

networks:
    default:
        external:
            name: nginx-proxy