version: '2'

services:

    php_apache:
        restart: "!restart!"
        build:
            context: ./php/apache
            args:
                - SITENAME=!domain!
            dockerfile: dockerfile-!php!/Dockerfile
        environment:
            - VIRTUAL_HOST=!domain!
        volumes_from:
            - volumes_source
        expose:
            - "80"

    mysql:
        restart: "!restart!"
        build:
            context: ./mysql
            dockerfile: ./dockerfile-!mysql!/Dockerfile
        volumes:
            - ../db/mysql:/var/lib/mysql
            - ../db/backup:/var/www/backup
        environment:
            MYSQL_DATABASE: site
            MYSQL_USER: site
            MYSQL_PASSWORD: site
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "!dbport!:3306"
        expose:
            - "3306"

    volumes_source:
        build: ./volumes/application
        volumes:
            - ../www/:/var/www/html
            - ./php-apache/hosts:/etc/hosts
            - ./php-apache/cacert.pem:/usr/lib/ssl/private/cacert.pem

networks:
    default:
        external:
            name: nginx-proxy